services:
  cleanarchitectureapi.api:
    image: cleanarchitectureapi.api
    container_name: api
    build:
      context: .
      dockerfile: src/CleanArchitectureApi.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings_Database=Server=${MSSQL_SERVER};Database=${MSSQL_DATABASE};User Id=${MSSQL_USERNAME};Password=${MSSQL_PASSWORD};TrustServerCertificate=True;
    ports:
      - "5000:8080"
      - "5001:8081"
    depends_on:
      - cleanarchitectureapi.db
    networks:
      - default
  
  cleanarchitectureapi.db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: db
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${MSSQL_PASSWORD}
    ports:
      - "1433:1433"
    volumes:
      - mssql-data:/var/opt/mssql
    networks:
      - default

  cleanarchitectureapi.seriLog:
    image: datalust/seq:latest
    container_name: seriLog
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5341:5341"
      - "9000:80"
    networks:
      - default
  
  cleanarchitectureapi.redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - default

volumes:
  mssql-data:

networks:
  default:
    driver: bridge
  
