services:
  cleanarchitectureapi.api:
    image: cleanarchitectureapi.api
    container_name: api
    build:
      context: .
      dockerfile: src/CleanArchitectureApi.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Database=Server=cleanarchitectureapi.db;Database=cleanarchitectureapi;User Id=sa;Password=Passw0rd!;TrustServerCertificate=True;
    depends_on:
      - cleanarchitectureapi.db
    networks:
      - default
        
  cleanarchitectureapi.db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: db
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Passw0rd!
    ports:
      - "1433:1433"
    volumes:
      - mssql-data:/var/opt/mssql
    networks:
      - default

volumes:
  mssql-data:
    
networks:
  default:
    driver: bridge
  
